Repository planetarium/snack.planetarium.dev, pull requests merged in 2022-09, with the labels that each got.

#154 Better `<table>` style
  themes/hugo-planetarium/assets/scss/style.scss
Labels: enhancement, Extra Small

#153 오픈 소스인 립플래닛 프로젝트에 기여 하기 전에 알아야 할 파일들
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/images/1.png
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/images/2.png
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/images/3.png
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/index.kor.md
  data/authors/hyekyung.toml
Labels: Small

#158 Add newlines in blockquotes
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/index.kor.md
Labels: Extra Small

#159 오픈그래프 이미지 추가
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/images/og.jpg
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/index.kor.md
Labels: Extra Small

#161 Changed Open Graph Image File
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/images/Libplanet_OpenGraph_Image.png
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/index.kor.md
Labels: Extra Small
