Repository planetarium/snack.planetarium.dev, pull requests merged in 2022-12, with the labels that each got.

#162 오픈소스, 블록체인 그리고 탈중앙 애플리케이션
  content/posts/2022/12/oss-blockchain-and-decentralized/images/og.jpg
  content/posts/2022/12/oss-blockchain-and-decentralized/index.kor.md
Labels: Small

#160 Delete og.jpg
  content/posts/2022/09/files-you-would-better-to-know-while-contributing-oss-projects/images/og.jpg
Labels: No Changes

#170 신뢰하지 않을 자유
  content/posts/2022/12/about-trustless/images/og.jpg
  content/posts/2022/12/about-trustless/index.kor.md
Labels: Medium
